version: 1.0.{build}
image: Visual Studio 2017
configuration: 
  - Debug
  - Release
platform: 
  - x86
  - x64
before_build:
  - nuget restore src/DSEngine/DSEngine.sln
build:
  project: src/DSEngine/DSEngine.sln
  verbosity: minimal
cache: c:\tools\vcpkg\installed\