trigger:
  batch: false # batch changes if true, start a new build for every push if false
  branches:
    exclude: [ gh-pages ] # branch names which will not

pr:
  autoCancel: false # indicates whether additional pushes to a PR should cancel in-progress runs for the same PR. Defaults to true
  branches:
    exclude: [ gh-pages ] # branch names which will not

jobs:
- job: 'Build with MSBuild'
  timeoutInMinutes: 0
  cancelTimeoutInMinutes: 0
  strategy:
    maxParallel: 99
  pool:
    vmImage: 'vs2017-win2016'
    demands:
    - msbuild
    - visualstudio

  steps:
  - task: NuGetToolInstaller@0
    displayName: 'Use NuGet 4.4.1'
    inputs:
      versionSpec: 4.4.1

  - task: NuGetCommand@2
    displayName: 'NuGet restore'
    inputs:
      restoreSolution: '$(Parameters.solution)'

  - task: VSBuild@1
    displayName: 'Build solution src/DSEngine/DSEngine.sln ($(BuildConfiguration)-$(BuildPlatform))'
    inputs:
      solution: '$(Parameters.solution)'
      vsVersion: 15.0
      platform: '$(BuildPlatform)'
      configuration: '$(BuildConfiguration)'
